﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MedicalModel_Exercise02
{
    public partial class MedicalModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"sex", @"sex"),new InputOutputColumnPair(@"smoker", @"smoker"),new InputOutputColumnPair(@"region", @"region")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"age", @"age"),new InputOutputColumnPair(@"bmi", @"bmi"),new InputOutputColumnPair(@"children", @"children")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"sex",@"smoker",@"region",@"age",@"bmi",@"children"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=22,NumberOfTrees=10,MaximumBinCountPerFeature=322,LearningRate=0.0708604068316017F,FeatureFraction=1F,LabelColumnName=@"charges",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
