
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MedicalModel_Exercise02
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MedicalModel.ModelInput sampleData = new MedicalModel.ModelInput()
            {
                Age = 19F,
                Sex = @"female",
                Bmi = 27.9F,
                Children = 0F,
                Region = @"southwest",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MedicalModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Charges with predicted Charges from sample data...\n\n");


            Console.WriteLine($"Age: {19F}");
            Console.WriteLine($"Sex: {@"female"}");
            Console.WriteLine($"Bmi: {27.9F}");
            Console.WriteLine($"Children: {0F}");
            Console.WriteLine($"Region: {@"southwest"}");
            Console.WriteLine($"Charges: {16884.92F}");


            Console.WriteLine($"\n\nPredicted Charges: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
